#WAP TO ACCEPT MARKS OF 6 STUDENT AND DISPLAY THEM IN A SORTED MANNER
MARKS=[]

P1=input("ENTER MARKS HERE: ")
MARKS.append(P1)

P2=input("ENTER MARKS HERE: ")
MARKS.append(P2)

P3=input("ENTER MARKS HERE: ")
MARKS.append(P3)

P4=input("ENTER MARKS HERE: ")
MARKS.append(P4)

P5=input("ENTER MARKS HERE: ")
MARKS.append(P5)

P6=input("ENTER MARKS HERE: ")
MARKS.append(P6)

P7=input("ENTER MARKS HERE: ")
MARKS.append(P7)

MARKS.sort()
print(MARKS)
