#WAP  TO STORE SEVEN FRUIT IN A LIST ENTERED BY THE USER
fruits=[]
F1=input("ENTER FRUIT NAME HERE : ")
fruits.append(F1)

F2=str(input("ENTER FRUIT NAME HERE : "))
fruits.append(F2)

f3=str(input("ENTER FRUIT NAME HERE : "))
fruits.append(f3)

f4=str(input("ENTER FRUIT NAME HERE : "))
fruits.append(f4)

f5=str(input("ENTER FRUIT NAME HERE : "))
fruits.append(f5)

f6=str(input("ENTER FRUIT NAME HERE : "))
fruits.append(f6)

f7=str(input("ENTER FRUIT NAME HERE : "))
fruits.append(f7)

print(fruits)
