DATA=["BHAKTI",89.70,23,"APPLE",False,"sarvadnys"]
print(DATA)


DATA.append("OM")
print(DATA) #Adds an item to the end of the list.


l1=[1,54,3,2,5,6,8,9,9,43]
l1.sort() #by default it sort ascending order
print(l1)

l1.reverse () #descending order 
print(l1)

l1.insert(2,55) #insert value at 2 index value 55
print(l1)

l1.pop(2) #pop at index 2 
print(l1) 

l1.remove(1) #remove  directly entering value.
print(l1)

l1.copy()
print(l1)

l1.clear() #Removes all items from the list.
print(l1)

