#WAP TO INPUT EIGHT NUMBERS FROM THE USER AND DISPLAY ALL UNIQUE NUMBERS (ONCE).
s=set()
print(type(s)) 

VALUE=int(input("ENTER NUMBER :"))
s.add(VALUE)

VALUE=input("ENTER NUMBER :")
s.add(VALUE)

VALUE=input("ENTER NUMBER :")
s.add(VALUE)

VALUE=input("ENTER NUMBER :")
s.add(VALUE)

VALUE=input("ENTER NUMBER :")
s.add(VALUE)

VALUE=input("ENTER NUMBER :")
s.add(VALUE)

VALUE=input("ENTER NUMBER :")
s.add(VALUE)

VALUE=input("ENTER NUMBER :")
s.add(VALUE)

print(s)
