#CREATE AN EMPTY DICTIONARY . ALLOW 4 FRIENDS TO ENTER THEIR FAVOURITE LANGUAGE AS VALUE AND USE KEY AS THEIR NAMES.ASSUME THAT THE NAME ARE UNIQUE.
DICT1={}
print(type(DICT1))

name=input("Enter name 1:")
lang=input("Enter favourite language")
DICT1.update({name:lang})

name=input("Enter name 1:")
lang=input("Enter favourite language")
DICT1.update({name:lang})

name=input("Enter name 1:")
lang=input("Enter favourite language")
DICT1.update({name:lang})

name=input("Enter name 1:")
lang=input("Enter favourite language")
DICT1.update({name:lang})

print(DICT1)

