'''
def add(a, b):
    return a + b

result = add(5, 3)
print("Sum is:", result)
'''

'''def greet(NAME,End):
    print("Good Day",NAME,End)

greet("BHARTI","Thank you!") #2 argument
greet("Bhakti","Thank you!") #2 argument
greet("Bhargavi","Thank you!") #2 argument '''



'''def greet(NAME,End):
    print("Good Day",NAME,End)

greet("BHARTI","Thank you!") #2 argument'''

a=int(input("Enter your number :"))
b=int(input("Enter your number :"))
c=int(input("Enter your number :"))
avg=(a+b+c)/3
print(avg)

a=avg() #function call 
print("THANK YOU !")
avg()
print("THANK YOU !")
avg() 