

#In Python, a function is a reusable block of code that performs a specific task. 
# You define a function once and can use (or "call") it many times.


"""
def function_name(parameters):
    # code block
    return result
"""

"""

FUNCTION DEFINITION
def HELLO():
    print("Hello, welcome!")

# Function call
HELLO()  # Function call 
"""

'''
def add(a, b):
    return a + b

result = add(5, 3)
print("Sum is:", result)
'''

# WAP to greet a user with “Good day” using functions.
def greet():
    print("Good Day")

greet()