'''
#SOME EXAMPLES OF VALID VARIABLE NAME
name	#Starts with a letter
_count	#Starts with underscore
value1	#Includes a digit, valid
user_name	#Underscores allowed
Name	#Case-sensitive; different from name
x	#Short, valid
'''
'''
#Invalid Variable Names
1name	#Starts with a number 
@value	#Contains special character @ 
user-name	#Hyphen is not allowed 
class	#It's a Python keyword 
my var	#Contains a space 
for	#Python reserved keyword 
'''