# DECLARING VARIABLE 
name="Bharti" #string type variable
age=22        #integer type number
cgpa=8.5      #floating type number
Apllicable=True #boolean variable
citizen=None    #none type variable 

#PRINTING VARIAVLE VALUES
print("student name is : ",name)
print("student age is : ",age)
print("student cgpa is : ",cgpa)
print("student is applicable ? : ",Apllicable)
print("student from America: ",citizen)