
##################################################### if else statement #######################################################################3
age=int(input("Enter age :"))
if (age<18):
    print("your are below 18")

else:
    print("you are above 18 ")

#WAP to print yes when the age entered by the user is greater than or equal to 18.
age=int(input("Enter your age : "))
if (age>=18):
    print("yes")
else:
    print("no")